/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register account
         * @description Create a new user account with the provided registration information.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                    "text/json": components["schemas"]["RegisterRequest"];
                    "application/*+json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthenticationResponseApiResponse"];
                        "application/json": components["schemas"]["AuthenticationResponseApiResponse"];
                        "text/json": components["schemas"]["AuthenticationResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate user and return a JWT token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthenticationResponseApiResponse"];
                        "application/json": components["schemas"]["AuthenticationResponseApiResponse"];
                        "text/json": components["schemas"]["AuthenticationResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate refresh token
         * @description Generate a new refresh token for the authenticated user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RefreshTokenRequest"];
                    "text/json": components["schemas"]["RefreshTokenRequest"];
                    "application/*+json": components["schemas"]["RefreshTokenRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RefreshTokenResponseApiResponse"];
                        "application/json": components["schemas"]["RefreshTokenResponseApiResponse"];
                        "text/json": components["schemas"]["RefreshTokenResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify email
         * @description Verify user's email using the provided token.
         */
        get: {
            parameters: {
                query?: {
                    Email?: string;
                    Token?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthenticationResponseApiResponse"];
                        "application/json": components["schemas"]["AuthenticationResponseApiResponse"];
                        "text/json": components["schemas"]["AuthenticationResponseApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-tree/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Knowledge Node
         * @description Retrieve a knowledge node by its ID within a specified workspace.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetKnowledgeNodeResponseApiResponse"];
                        "application/json": components["schemas"]["GetKnowledgeNodeResponseApiResponse"];
                        "text/json": components["schemas"]["GetKnowledgeNodeResponseApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Knowledge Tree
         * @description Create a knowledge tree for a specified workspace using provided file paths.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreatedKnowledgetreeRequest"];
                    "text/json": components["schemas"]["CreatedKnowledgetreeRequest"];
                    "application/*+json": components["schemas"]["CreatedKnowledgetreeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RabbitMqSendingResponseApiResponse"];
                        "application/json": components["schemas"]["RabbitMqSendingResponseApiResponse"];
                        "text/json": components["schemas"]["RabbitMqSendingResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-tree/node/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Knowledge Node by ID
         * @description Retrieve a knowledge node by its ID.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    nodeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetKnowledgeNodeResponseApiResponse"];
                        "application/json": components["schemas"]["GetKnowledgeNodeResponseApiResponse"];
                        "text/json": components["schemas"]["GetKnowledgeNodeResponseApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get workspace details
         * @description Retrieve details of a specific workspace by its ID.
         */
        get: {
            parameters: {
                query?: {
                    workspaceId?: string;
                };
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkspaceDetailResponseApiResponse"];
                        "application/json": components["schemas"]["WorkspaceDetailResponseApiResponse"];
                        "text/json": components["schemas"]["WorkspaceDetailResponseApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get workspace details by user ID
         * @description Retrieve details of a specific workspace by its ID.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkspaceDetailResponseApiResponse"];
                        "application/json": components["schemas"]["WorkspaceDetailResponseApiResponse"];
                        "text/json": components["schemas"]["WorkspaceDetailResponseApiResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a new workspace
         * @description Create a new workspace with the provided details.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateWorkspaceRequest"];
                    "text/json": components["schemas"]["CreateWorkspaceRequest"];
                    "application/*+json": components["schemas"]["CreateWorkspaceRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkspaceDetailResponseApiResponse"];
                        "application/json": components["schemas"]["WorkspaceDetailResponseApiResponse"];
                        "text/json": components["schemas"]["WorkspaceDetailResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthenticationResponse: {
            refreshToken: string | null;
            accessToken: string | null;
            /** Format: uuid */
            id: string;
            email: string | null;
            fullName: string | null;
            phoneNumber: string | null;
            emailVerified: boolean;
        };
        AuthenticationResponseApiResponse: {
            success?: boolean;
            message?: string | null;
            data?: components["schemas"]["AuthenticationResponse"];
            /** Format: int32 */
            statusCode?: number;
            meta?: unknown;
            errorCode?: string | null;
        };
        CreateWorkspaceRequest: {
            name: string | null;
            description?: string | null;
            fileIds?: string[] | null;
        };
        CreatedKnowledgetreeRequest: {
            workspaceId: string | null;
            filePaths: string[] | null;
        };
        Evidence: {
            id?: string | null;
            sourceId?: string | null;
            sourceName?: string | null;
            chunkId?: string | null;
            text?: string | null;
            /** Format: int32 */
            page?: number;
            /** Format: float */
            confidence?: number;
            /** Format: date-time */
            createdAt?: string;
            language?: string | null;
            sourceLanguage?: string | null;
            hierarchyPath?: string | null;
            concepts?: string[] | null;
            keyClaims?: string[] | null;
            questionsRaised?: string[] | null;
            /** Format: float */
            evidenceStrength?: number;
        };
        GapSuggestion: {
            id?: string | null;
            suggestionText?: string | null;
            targetNodeId?: string | null;
            targetFileId?: string | null;
            /** Format: float */
            similarityScore?: number;
        };
        GetKnowledgeNodeResponse: {
            nodeId: string | null;
            nodeName: string | null;
            description: string | null;
            tags: string[] | null;
            /** Format: int32 */
            level: number;
            /** Format: int32 */
            sourceCount: number;
            evidences: components["schemas"]["Evidence"][] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            childNodes: components["schemas"]["GetKnowledgeNodeResponse"][] | null;
            gapSuggestions?: components["schemas"]["GapSuggestion"][] | null;
        };
        GetKnowledgeNodeResponseApiResponse: {
            success?: boolean;
            message?: string | null;
            data?: components["schemas"]["GetKnowledgeNodeResponse"];
            /** Format: int32 */
            statusCode?: number;
            meta?: unknown;
            errorCode?: string | null;
        };
        LoginRequest: {
            /** @description User's email address */
            email: string | null;
            /** @description User's password */
            password: string | null;
            /** @description The IP address of the client making the request */
            ipAddress: string | null;
            /** @description The User-Agent string of the client making the request */
            userAgent: string | null;
            /** @description An optional device fingerprint to uniquely identify the device */
            deviceFingerprint?: string | null;
        };
        RabbitMqSendingResponse: {
            messageId: string | null;
            /** Format: date-time */
            sentAt: string;
            status?: string | null;
        };
        RabbitMqSendingResponseApiResponse: {
            success?: boolean;
            message?: string | null;
            data?: components["schemas"]["RabbitMqSendingResponse"];
            /** Format: int32 */
            statusCode?: number;
            meta?: unknown;
            errorCode?: string | null;
        };
        RefreshTokenRequest: {
            /** Format: uuid */
            userId: string;
            token: string | null;
            ipAddress: string | null;
            userAgent: string | null;
            deviceFingerprint?: string | null;
        };
        RefreshTokenResponse: {
            token: string | null;
            /** Format: date-time */
            expiresAt: string;
        };
        RefreshTokenResponseApiResponse: {
            success?: boolean;
            message?: string | null;
            data?: components["schemas"]["RefreshTokenResponse"];
            /** Format: int32 */
            statusCode?: number;
            meta?: unknown;
            errorCode?: string | null;
        };
        RegisterRequest: {
            /** @description User's email address */
            email: string | null;
            /** @description User's password */
            password: string | null;
            /** @description User's full name */
            fullName: string | null;
            /** @description User's phone number */
            phoneNumber: string | null;
        };
        WorkspaceDetailResponse: {
            workspaceId: string | null;
            name: string | null;
            description: string | null;
            ownerId: string | null;
            ownerName: string | null;
            fileIds: string[] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        WorkspaceDetailResponseApiResponse: {
            success?: boolean;
            message?: string | null;
            data?: components["schemas"]["WorkspaceDetailResponse"];
            /** Format: int32 */
            statusCode?: number;
            meta?: unknown;
            errorCode?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
